### ISSUE TITLE
Can't to connect to mongodb container by alias

### ISSUE THREAD

**Issue by fr05t1k** [docker-library/golang#112]
### Expected behavior
I want to connect to mongo db by container alias.
### Actual behavior
Container alias is resolved to host ip address.
### Information

Diagnostic ID: AC37E62B-DFB3-4F03-8A00-7FC78E1ABE4E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. I have this compose file:
```yml
version: '2'
volumes:
  mongodb:
    driver: local
services:
    mongodb:
        image: mongo:latest
        volumes:
            - "mongodb:/data/db"
    wallet:
        image: golang:wheezy

```
2. So run it `docker-compose run wallet bash`
3. ping mongodb output:
```
PING mongodb (172.18.0.2): 48 data bytes
56 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.241 ms
56 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=0.121 ms
56 bytes from 172.18.0.2: icmp_seq=2 ttl=64 time=0.113 ms
```
4. Then run `go run -v main.go`:
```go
	for {
		ips, err := net.LookupHost(mongoConnectionString)
		fmt.Println(ips)
		fmt.Println("Trying to connect to: " + mongoConnectionString)
		session, err := mgo.Dial(mongoConnectionString)

		if err == nil {

			fmt.Println("Connection succeed")

			session.SetMode(mgo.Monotonic, true)
			DB = session.DB(mongoDBName);
			return
		}

	}
```
output:
```
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
[125.235.4.59]
Trying to connect to: mongodb
```
