### ISSUE TITLE
go build fails to read vcs info when .git is owned by a different user

### ISSUE THREAD

**Issue by forsaken628** [docker-library/golang#452]
golang:bullseye built-in install git(2.30.2) which break our CI/CD system.

https://github.com/golang/go/issues/53532

**Comment by TeddiO** [comment]
Can confirm a similar issue in our CI/CD pipelines. In addition if you run `go build` with the `-v` flag you get the extra output:

```
fatal: detected dubious ownership in repository at '/__w/<path>'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/<path>
```

1.19.4 and previous are functioning as intended .

**Comment by peterdeme** [comment]
The interesting thing is that `actions/checkout@v3` even adds the current directory to the safe directories by default.

But for some reason it doesn't work. If you manually add it, it starts to work.

```yaml
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
```
